# Generated by Django 3.2.25 on 2025-05-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(max_length=50)),
                ('bedrooms', models.FloatField()),
                ('bathrooms', models.FloatField()),
                ('home_size', models.IntegerField()),
                ('home_type', models.CharField(max_length=50)),
                ('last_sold', models.DateField()),
                ('last_sold_price', models.FloatField()),
                ('link', models.URLField()),
                ('price', models.FloatField()),
                ('property_size', models.IntegerField()),
                ('rent_price', models.FloatField()),
                ('rent_zestimate', models.FloatField()),
                ('rent_zestimate_last_updated', models.DateField()),
                ('tax_value', models.FloatField()),
                ('tax_year', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('zestimate', models.FloatField()),
                ('zestimate_last_updated', models.DateField()),
                ('zillow_id', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
            ],
        ),
    ]
