# Generated by Django 3.2.25 on 2025-05-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='home_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='last_sold',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='last_sold_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_zestimate_last_updated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='zestimate_last_updated',
            field=models.DateField(null=True),
        ),
    ]
