# Generated by Django 3.2.25 on 2025-05-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250512_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='zestimate',
            field=models.FloatField(null=True),
        ),
    ]
