# Generated by Django 3.2.25 on 2025-05-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_house_zestimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='home_size',
            field=models.FloatField(null=True),
        ),
    ]
