# Generated by Django 3.2.25 on 2025-05-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_house_home_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='property_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='year_built',
            field=models.IntegerField(null=True),
        ),
    ]
