# Generated by Django 3.2.25 on 2025-05-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250512_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.FloatField(null=True),
        ),
    ]
