# Generated by Django 3.2.25 on 2025-05-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20250512_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rent_zestimate',
            field=models.FloatField(null=True),
        ),
    ]
